### ISSUE TITLE
Is this repo still needed?

### ISSUE THREAD

**Issue by TheMcMurder** [esm-bundle/chai#17]
I'm cleaning up `esm-bundle` projects so they are easier to maintain and migrating them off `travis-ci`.

Is this project/repo still needed? How is it being used right now?

**Comment by joeldenning** [comment]
cc @LarsDenBakker

**Comment by LarsDenBakker** [comment]
Yes it's needed, we recommend it at https://modern-web.dev/ for people who want to use chai as an es module.

I recently lost access to the esm-bundle org, not sure if that was intentional?

**Comment by TheMcMurder** [comment]
@LarsDenBakker thanks for the info. I'll work on migrating this one to the new CI system.
