### ISSUE TITLE
Publish failure 4.3.5

### ISSUE THREAD

**Issue by edoardocavazza** [esm-bundle/chai#72]
It seems that the 4.3.5 has not been correctly published to npm.

See https://github.com/esm-bundle/chai/actions/runs/826320941

**Comment by taymoork2** [comment]
@joeldenning

A simpler solution might be to just bump to `v4.3.6` and see if that fixes it
I don't use release-it personally so I'm unsure if there are any existing solutions to an issue like this or if just bumping to a new version will fix it

https://github.com/release-it/release-it/blob/master/docs/ci.md#github-actions

**Comment by joeldenning** [comment]
4.3.5 is the wrong version to publish this as, since chai@4.3.5 doesn't exist. So https://github.com/esm-bundle/chai/pull/61 was an incorrect pull request. Instead, it should be published as 4.3.4-fix.0

**Comment by joeldenning** [comment]
The latest version is published as `@esm-bundle/chai@4.3.4-fix.0`
